INSERT INTO Genre VALUES ('Comedie')
INSERT INTO Genre VALUES ('Drame')
INSERT INTO Genre VALUES ('Romance')
INSERT INTO Genre VALUES ('Historique')
INSERT INTO Genre VALUES ('Western')
INSERT INTO Genre VALUES ('Horreur')
INSERT INTO Genre VALUES ('Fantaisie')
INSERT INTO Genre VALUES ('Thriller')
INSERT INTO Genre VALUES ('Aventure')
INSERT INTO Genre VALUES ('Péplum')
INSERT INTO Genre VALUES ('science-fiction')
INSERT INTO Genre VALUES ('érotique')


INSERT INTO Categories VALUES ('Documentaires')
INSERT INTO Categories VALUES ('Films')
INSERT INTO Categories VALUES ('Séries')
INSERT INTO Categories VALUES ('Divertissements')


INSERT INTO Langues VALUES ('Francais')
INSERT INTO Langues VALUES ('Anglais')
INSERT INTO Langues VALUES ('Allemand')
INSERT INTO Langues VALUES ('Japonais')
INSERT INTO Langues VALUES ('Espagnol')
INSERT INTO Langues VALUES ('Italien')
INSERT INTO Langues VALUES ('Chinois')
INSERT INTO Langues VALUES ('Russe')
INSERT INTO Langues Values ('Naavi')
